--1. 테이블 만들기
CREATE TABLE TB_CATEGORY(
    NAME VARCHAR2(10),
    USE_YN CHAR(1) DEFAULT 'Y'
);

--2. 테이블 만들기
CREATE TABLE TB_CLASS_TYPE(
    NO VARCHAR2(5) PRIMARY KEY,
    NAME VARCHAR2(10)
);

--3. TB_CATEGORY NAME컬럼에 PRIMARY KEY 생성
ALTER TABLE TB_CATEGORY ADD PRIMARY KEY(NAME);

--4. TB_CLASS_TYPE NAME컬럼에 NOT NULL 생성
ALTER TABLE TB_CLASS_TYPE MODIFY NAME NOT NULL;

--5. 컬럼명 NO는 타입유지, 크기 10 변경/ 컬럼명 NAME은 타입 유지, 크기 20 변
ALTER TABLE TB_CATEGORY MODIFY NAME VARCHAR(20);
ALTER TABLE TB_CLASS_TYPE MODIFY NAME VARCHAR2(20);
ALTER TABLE TB_CLASS_TYPE MODIFY NO VARCHAR2 (10);

--6. 컬럼 이름 바꾸기
ALTER TABLE TB_CATEGORY RENAME COLUMN NAME TO CATEGORY_NAME;
ALTER TABLE TB_CLASS_TYPE RENAME COLUMN NO TO CLASS_TYPE_NO;
ALTER TABLE TB_CLASS_TYPE RENAME COLUMN NAME TO CLASS_TYPE_NAME;

--7. PRIMARY KEY 이름 변경
ALTER TABLE TB_CATEGORY RENAME CONSTRAINT SYS_C007218 TO PK_CATEGORY_NAME;
ALTER TABLE TB_CLASS_TYPE RENAME CONSTRAINT SYS_C007217 TO PK_CLASS_TYPE_NO;

--8.INSERT
INSERT INTO tb_category
VALUES ('공학', 'Y');

INSERT INTO tb_category
VALUES ('자연과학','Y');

INSERT INTO tb_category
VALUES ('의학','Y');

INSERT INTO tb_category 
VALUES ('예체능','Y');

INSERT INTO tb_category
VALUES ('인문사회','Y');

COMMIT;

--9
ALTER TABLE TB_DEPARTMENT ADD CONSTRAINT FK_DEPARTMENT_CATEGORY FOREIGN KEY(CATEGORY)
    REFERENCES TB_CATEGORY(CATEGORY_NAME); 
    
    
--10.
GRANT CREATE VIEW TO CHOON;

create OR REPLACE VIEW VW_학생일반정보(학번, 학생이름, 주소)
AS (SELECT STUDENT_NO, STUDENT_NAME, STUDENT_ADDRESS
    FROM TB_STUDENT);
    
SELECT * FROM "VW_학생일반정보";

--11.
CREATE OR REPLACE VIEW VW_지도면담(학생이름, 학과이름, 지도교수이름)
AS SELECT STUDENT_NAME, DEPARTMENT_NAME, PROFESSOR_NAME
    FROM tb_student
    LEFT JOIN tb_department USING (DEPARTMENT_NO)
    LEFT JOIN tb_professor ON (COACH_PROFESSOR_NO = PROFESSOR_NO )
    ORDER BY DEPARTMENT_NAME;

SELECT * FROM "VW_지도면담";

--12.
CREATE OR REPLACE VIEW VW_학과별학생수
AS SELECT DEPARTMENT_NAME, COUNT(STUDENT_NO) STUDENT_COUNT
FROM  TB_DEPARTMENT
JOIN  tb_student USING (DEPARTMENT_NO)
GROUP BY DEPARTMENT_NO, DEPARTMENT_NAME;

SELECT * FROM "VW_학과별학생수";

--13. 
UPDATE VW_학생일반정보
SET 학생이름 = '김솔지'
WHERE 학번 = 'A213046';

--14. VIEW 만들때 OR REPLACE 없이 생성하면 됨

--15. 최근 3년동안 수강인원 제일 많았던 3과목
SELECT CLASS_NAME,COUNT(STUDENT_NO), RANK() OVER (ORDER BY COUNT(STUDENT_NO) DESC) RK
FROM TB_GRADE
JOIN TB_CLASS USING (CLASS_NO)
WHERE TERM_NO >= 200501 
GROUP BY CLASS_NAME
ORDER BY COUNT(STUDENT_NO) DESC;

SELECT CLASS_NO, CLASS_NAME, COUNT(STUDENT_NO) AS "누적수강생수(명)"
FROM (SELECT CLASS_NO, CLASS_NAME, COUNT(STUDENT_NO), RANK() OVER (ORDER BY COUNT(STUDENT_NO) DESC) RK
FROM TB_GRADE
JOIN TB_CLASS USING (CLASS_NO)
WHERE TERM_NO >= 200501 
GROUP BY CLASS_NO, CLASS_NAME
ORDER BY COUNT(STUDENT_NO) DESC)
WHERE ROWNUM  < 4;

SELECT CLASS_NO, CLASS_NAME, COUNT(STUDENT_NO)
FROM TB_GRADE
JOIN TB_CLASS USING (CLASS_NO)
WHERE TERM_NO >= 200501 
GROUP BY CLASS_NO, CLASS_NAME
ORDER BY COUNT(STUDENT_NO) DESC;

SELECT *
FROM (SELECT CLASS_NO, CLASS_NAME, COUNT(STUDENT_NO)
FROM TB_GRADE
JOIN TB_CLASS USING (CLASS_NO)
WHERE TERM_NO >= 200501 
GROUP BY CLASS_NO, CLASS_NAME
ORDER BY COUNT(STUDENT_NO) DESC)
WHERE ROWNUM <4;