--1
INSERT INTO TB_CLASS_TYPE VALUES (01, '전공필수');
INSERT INTO TB_CLASS_TYPE VALUES (02, '전공선택');
INSERT INTO TB_CLASS_TYPE VALUES (03, '교양필수');
INSERT INTO TB_CLASS_TYPE VALUES (04, '교양선택');
INSERT INTO TB_CLASS_TYPE VALUES (05, '논문지도');

--2
CREATE TABLE TB_학생일반정보
    AS  SELECT STUDENT_NO, STUDENT_NAME, STUDENT_ADDRESS
        FROM tb_student;
        
--3. 국어국문학과 학생들의 정보만 포함된 학과 정보 테이블
CREATE TABLE TB_국어국문학과
AS SELECT STUDENT_NO 학번, STUDENT_NAME 학생이름, TO_CHAR(TO_DATE(SUBSTR(STUDENT_SSN,1,2),'RR'),'YYYY') 출생년도, PROFESSOR_NAME 교수이름
    FROM TB_STUDENT
    JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
    LEFT JOIN tb_professor ON (COACH_PROFESSOR_NO = PROFESSOR_NO)
    WHERE department_name = '국어국문학과';
    
    SELECT * FROM TB_국어국문학과;
    DROP TABLE TB_국어국문학과;
 
--4
UPDATE TB_DEPARTMENT
SET (CAPACITY * 1.1);

--5
UPDATE TB_STUDENT
SET STUDENT_ADDRESS = '서울시 종로구 숭인동 181-21'
WHERE student_no = 'A413042';

COMMIT;
--6
UPDATE TB_STUDENT
SET STUDENT_SSN  = SUBSTR(STUDENT_SSN,1,6 );

--7

--8
DELETE FROM TB_GRADE
WHERE 

















