CREATE USER KH IDENTIFIED BY KH;
GRANT RESOURCE, CONNECT TO KH;
GRANT CREATE TABLE TO KH;
GRANT CREATE VIEW TO KH;
GRANT CREATE SEQUENCE TO KH;
GRANT CREATE SYNONYM TO KH;
GRANT CREATE PROCEDURE TO KH;
GRANT CREATE TRIGGER TO KH;
